add_item:
  fields:
    list_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    item_name:
      required: true
      selector:
        text:
    entry_id:
      required: false
      selector:
        text:

complete_item:
  fields:
    item_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    entry_id:
      required: false
      selector:
        text:

update_item:
  fields:
    list_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    item_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    item_name:
      required: true
      selector:
        text:
    entry_id:
      required: false
      selector:
        text:

set_item_quantity:
  fields:
    list_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    item_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    quantity:
      required: true
      selector:
        number:
          min: 1
          max: 1000
          mode: box
    entry_id:
      required: false
      selector:
        text:

delete_item:
  fields:
    item_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    entry_id:
      required: false
      selector:
        text:

create_list:
  fields:
    name:
      required: true
      selector:
        text:
    entry_id:
      required: false
      selector:
        text:

activate_list:
  fields:
    list_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    entry_id:
      required: false
      selector:
        text:

reorder_items:
  fields:
    list_id:
      required: true
      selector:
        number:
          min: 1
          mode: box
    status:
      required: true
      selector:
        select:
          options:
            - active
            - later
    item_ids:
      required: true
      selector:
        object:
    entry_id:
      required: false
      selector:
        text:
